dependencies:
  - name: elasticsearch
    version: 7.9.2
    repository: https://helm.elastic.co
    condition: nuxeo.elasticsearch.deploy
    alias: elasticsearch
    tags:
      - elasticsearch
  - name: kafka
    version: ~0.20.8
    repository: http://storage.googleapis.com/kubernetes-charts-incubator
    condition: nuxeo.kafka.deploy
    alias: kafka
    tags:
      - kafka
  - name: mongodb
    version: ~7.14.2
    repository: https://charts.bitnami.com/bitnami
    condition: nuxeo.mongodb.deploy
    alias: mongodb
    tags:
      - mongodb
  - name: postgresql
    version: ~9.8.4
    repository: https://charts.bitnami.com/bitnami
    condition: nuxeo.postgresql.deploy
    alias: postgresql
    tags:
      - postgresql
  - name: redis
    version: ~11.2.1
    repository: https://charts.bitnami.com/bitnami
    alias: redis
    condition: nuxeo.redis.deploy
    tags:
      - redis
